[colors]
background = '#2c2d30'
foreground = '#b1b4b9'
selection-background = '#3e4045'
selection-foreground = '#b1b4b9'
cursor = '#a3b3cc'
black = '#191a1c'
red = '#e16d77'
green = '#99bc80'
yellow = '#dfbe81'
blue = '#68aee8'
magenta = '#c27fd7'
cyan = '#5fafb9'
white = '#dcdfe4'
light_black = '#282c34'
light_red = '#e06c75'
light_green = '#98c379'
light_yellow = '#e5c07b'
light_blue = '#61afef'
light_magenta = '#c678dd'
light_cyan = '#56b6c2'
light_white = '#dcdfe4'
